version: "3"

services:
  # Application

  database:
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=app
    volumes:
      - "postgresql_data:/bitnami/postgresql"

  db-test:
    image: postgres:13
    restart: always
    container_name: tests-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

volumes:
  postgresql_data:
    driver: local
